server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: group1


eureka:
  client:
    service-url:
      defaultZone: http://Eureka01:7001/eureka/, http://Eureka02:7002/eureka/



  instance:
    instance-id: receive-8803
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
