server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: localhost:2181

#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloudpayment?serverTimezone=UTC #useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: rootroot

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
##      defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://Eureka01:7001/eureka/, http://Eureka02:7002/eureka/
#  instance:
#    instance-id: consumer-order
#    prefer-ip-address: true
